- name: Ensure GCS bucket for tracking exists
  ansible.builtin.command:
    cmd: gsutil ls -b gs://{{ gcp_bucket_tracking_name }}
  register: bucket_tracking_exists
  failed_when: false

- name: Create GCS bucket for tracking if not exists
  ansible.builtin.command:
    cmd: gsutil mb -l {{ gcp_bucket_location }} gs://{{ gcp_bucket_tracking_name }}
  when: bucket_tracking_exists.rc != 0