- name: Check if Kubernetes Engine API is enabled
  ansible.builtin.command:
    cmd: gcloud services list --enabled --filter="container.googleapis.com" --format="value(config.name)"
  register: gke_api_status
  failed_when: false

- name: Enable Kubernetes Engine API
  ansible.builtin.command:
    cmd: gcloud services enable container.googleapis.com
  when: gke_api_status.stdout.strip() == ""
  register: enable_gke_api
  changed_when: enable_gke_api.rc == 0

- name: Ensure GKE cluster exists
  ansible.builtin.command:
    cmd: gcloud container clusters describe {{ gke_cluster_name }} --zone {{ gke_cluster_zone }}
  register: gke_cluster
  failed_when: false

- name: Create GKE cluster if it doesn't exist
  ansible.builtin.command:
    cmd: gcloud container clusters create {{ gke_cluster_name }} --zone {{ gke_cluster_zone }} --num-nodes {{ gke_initial_node_count }} --machine-type {{ gke_machine_type }}
  when: gke_cluster.rc != 0

- name: Get GKE credentials for kubectl access
  ansible.builtin.command:
    cmd: gcloud container clusters get-credentials {{ gke_cluster_name }} --zone {{ gke_cluster_zone }}