- name: Add Bitnami Helm repository
  ansible.builtin.command:
    cmd: helm repo add bitnami https://charts.bitnami.com/bitnami
  when: not lookup('file', '~/.cache/helm/repository/bitnami-index.yaml', errors='ignore')

- name: Update Helm repository
  ansible.builtin.command:
    cmd: helm repo update

- name: Pull the Bitnami MLflow Helm chart
  ansible.builtin.command:
    cmd: helm pull bitnami/mlflow --untar
  args:
    chdir: /tmp
  when: not lookup('file', '/tmp/mlflow/Chart.yaml', errors='ignore')

- name: Install or upgrade MLflow using Bitnami Helm chart
  ansible.builtin.command:
    cmd: >
      helm upgrade --install my-mlflow
      bitnami/mlflow
      -f {{ mlflow_values_path }}
      --namespace {{ k8s_namespace }}
  register: helm_install